[".config/dotfiles/fzf/key-bindings.bash"]
  type = "file"
  url = "https://raw.githubusercontent.com/junegunn/fzf/master/shell/key-bindings.bash"
  refreshPeriod = "24h"
[".config/dotfiles/fzf/completion.bash"]
  type = "file"
  url = "https://raw.githubusercontent.com/junegunn/fzf/master/shell/completion.bash"
  refreshPeriod = "24h"
[".config/dotfiles/fzf/key-bindings.fish"]
  type = "file"
  url = "https://raw.githubusercontent.com/junegunn/fzf/master/shell/key-bindings.fish"
  refreshPeriod = "24h"
[".config/fish/completions/docker.fish"]
  type = "file"
  url = "https://raw.githubusercontent.com/docker/docker-ce/master/components/cli/contrib/completion/fish/docker.fish"
  refreshPeriod = "24h"
